### ISSUE TITLE
Feedback for V0.3

### ISSUE THREAD

**Issue by okkhoy** [CS2103JAN2017-T09-B3/main#72]
## Admin stuff

- @ivankws @vane1992  please update your mugshots in the about us page to show your full face clearly!
- links to your profiles are not properly done, it shows raw text. please fix that

------

## Readme

- The screenshot of your app is different in readme.md and the user guide. Please fix it.

-----

## User guide

- **MyPotato** reads MyPotato, Mypotato, myPotato is different places, please ensure consistency
- `add` command: how will you add a floating tasks? there is no mention about that in your user guide
- `find` command: why the restriction on case sensitive search? think from a user's perspective, if I have a 100 tasks, and there is one specific one about "lunch with Advisor" if I have to remember "Advisor" as against "advisor", the find command becomes quite useless, no?
- `delete` command: how is delete deadline different from `edit` to remove deadline? it is a nice thing to have, just may be clarify in the user guide.
- `undo` command: can you undo an edit? can you undo clear? if not, may be you can think if they are useful features to have. if you can, need to add that in the user guide.
- `save` command: is it only for back up operation? what happens if you save -> close the app -> open? where does it read the data from?

<br>

- Are there any additional features / commands you are providing? if so, please mention them in the user guide.
- The 'Command summary' section will be used heavily by our testers. Try to make it easy to use as possible. e.g. give examples for each command.
- Try adding few screen captures where relevant.

-----

## Developer guide

- 3.1 Architecture
  - do you have the feature to connect to web and do something there? if not, please update the architecture to reflect the same
- 3.2 UI Component
  - nitpick: you can use backticks to show code related and command related stuff on github e.g: "/src/main/java/seedu/myPotato/ui"
- 3.3 Logic component
  - please check how sequence diagrams are written; there are some minor misses in your attempt
  - references to `person` still exist
- Section 3 general comments:
  - Suggested additions:
    - Explain how your design support undo/redo. There are multiple ways this can be done, so it will be useful to explain how you do it and why you chose to do it that way.
    - Similarly, you can explain other interesting design decisions you made.

- 5.0 Testing
  - It may be more practical to give a few examples of interesting test cases and explain the thinking behind how you arrived at those test cases, rather than try to give a comprehensive list of all test cases.

- Appendix A
  - Please freeze the user stories and remove the line `{more to be added!}`

- Appendix C
  - Still talks of `person`

@myduyhoanglong @e0011840 @ivankws @vane1992  for your action!

**Comment by e0011840** [comment]
Noted with Thanks
